name: CI

on:
    pull_request:
        branches:
            - main

jobs:
    check:
        name: Check
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest, macOS-latest, windows-latest ]
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Install toolchain
              id: toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: 1.70.0
                  override: true
                  components: rustfmt, clippy

            - name: Fix toolchains diff
              run: rustup component remove rust-src --toolchain stable

            - name: Cache dependencies
              uses: actions/cache@v1.0.1
              with:
                  path: target
                  key: pr-build-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('./Cargo.lock') }}

            - name: Run check
              uses: actions-rs/cargo@v1
              with:
                  command: check

            - name: Run test
              uses: actions-rs/cargo@v1
              with:
                  command: test

            - name: Run fmt
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --all -- --check

            - name: Run clippy
              uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: -- -D warnings
